# compose.yaml
name: influxdb3
services:
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - type: bind
        source: ./data/influxdb3/core/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: ./data/influxdb3/core/plugins
        target: /var/lib/influxdb3/plugins

  influxdb3-explorer:
    container_name: influxdb3-explorer
    image: influxdata/influxdb3-ui:1.5.0
    ports:
      - 8888:80
    volumes:
      - type: bind
        source: ./data/influxdb3/ui/config
        target: /app-root/config
      - type: bind
        source: ./data/influxdb3/ui/db
        target: /db
    command: ["--mode=admin"]
